# Generated by Django 4.0.4 on 2022-05-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LazyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LazyPortfolioTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtesting_data.lazyportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('inception_date', models.DateField()),
                ('equivalents', models.ManyToManyField(blank=True, null=True, to='backtesting_data.ticker')),
                ('portfolio', models.ManyToManyField(through='backtesting_data.LazyPortfolioTicker', to='backtesting_data.lazyportfolio')),
            ],
        ),
        migrations.AddField(
            model_name='lazyportfolioticker',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtesting_data.ticker'),
        ),
    ]
