# Generated by Django 4.0.4 on 2022-05-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lazyportfolioticker',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='equivalents',
            field=models.ManyToManyField(blank=True, to='backtesting_data.ticker'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
